name: Composer

on: [ push ]

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    composer:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ '8.2', '8.3', '8.4', '8.5' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@2.36.0
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
                    tools: symfony
                    extensions: ast, iconv

            -   name: Install Composer deps
                uses: ramsey/composer-install@v3
                with:
                    composer-options: --no-scripts

            -   name: Install Composer Normalize
                uses: ramsey/composer-install@v3
                with:
                    working-directory: './vendor-bin/cn'

            -   name: Run Composer
                run: |
                    symfony security:check
                    composer val:composer
