name: PSalm

on: [ push ]

jobs:
    psalm:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ '7.4', '8.0', '8.1' ]
                symfony: [ '~4.4', '~5.4', '~6.0' ]

        steps:
            -   name: Checkout
                # This combination is not installable
                if: |
                    false == (matrix.php != '7.4' && matrix.symfony != '~6.0')
                uses: actions/checkout@v2

            -   name: Setup PHP
                # This combination is not installable
                if: |
                    false == (matrix.php != '7.4' && matrix.symfony != '~6.0')
                uses: shivammathur/setup-php@2.16.0
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
                    extensions: ast, iconv

            -   name: Get Composer Cache Directory
                # This combination is not installable
                if: |
                    false == (matrix.php != '7.4' && matrix.symfony != '~6.0')
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Composer's dependencies
                # This combination is not installable
                if: |
                    false == (matrix.php != '7.4' && matrix.symfony != '~6.0')
                uses: actions/cache@v2.1.7
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: php-composer-dependencies-cache

            -   name: Fix Symfony version
                # This combination is not installable
                if: |
                    false == (matrix.php != '7.4' && matrix.symfony != '~6.0')
                run: |
                    composer req symfony/flex --no-update
                    composer config extra.symfony.require "${{ matrix.symfony }}"

            -   name: Remove Rector
                # This combination is not installable
                if: |
                    false == (matrix.php != '7.4' && matrix.symfony != '~6.0')
                run: |
                    composer rem rector/rector --dev --no-update

            -   name: Install Composer deps
                # This combination is not installable
                if: |
                    false == (matrix.php != '7.4' && matrix.symfony != '~6.0')
                # Do not install all bin deps, but individually install the required ones
                # The second update is to make Flex able to do its job
                run: |
                    composer update --no-interaction --no-scripts
                    composer update --no-interaction --no-scripts
                    composer bin phpunit update

            -   name: Run PSalm
                # This combination is not installable
                if: |
                    false == (matrix.php != '7.4' && matrix.symfony != '~6.0')
                run: |
                    ./vendor/bin/psalm
